version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: uopp-postgres
    environment:
      POSTGRES_DB: uopp_ai_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - uopp-network

volumes:
  postgres_data:

networks:
  uopp-network:
    driver: bridge
